### ISSUE TITLE
TVDB Support = Ordering / Language Support

### ISSUE THREAD

**Issue by eduo** [meermanr/TVSeriesRenamer#14]
I can't believe I've been using this script for ten years :-D

Just a quick "issue" to ask if TheTVDB support is planned at all or not really.

Adding TheTVDB would open two additional options: Selecting ordering preference and selecting alternate languages.

http://thetvdb.com/?tab=seasonall&id=267440&lid=7

vs

http://thetvdb.com/?tab=seasonall&id=267440&lid=16

**Comment by meermanr** [comment]
Closing as "won't fix". (Sorry!)
