### ISSUE TITLE
Episode Titles Fetched from "epguide.com" Sometimes Contain Junk

### ISSUE THREAD

**Issue by the-real-tokai** [meermanr/TVSeriesRenamer#21]
I usually fetch titles via "epguide.com". In some cases the resulting filenames contain superfluous extra junk that is not filtered properly (or could/should be filtered).

E.g. Episodes of season 1 and 2 of http://epguides.com/realhusbandsofhollywood/ have some "(60 min)" marker at the end which is not properly stripped and ends up as `Series Title S00E00 Episode Title--a- (60 min).suffix`.

Another problem that I sometimes notice is that `&amp;` ends up as part of the episode title in the filenames rather than just `&`, e.g. `Series S00E00 Foo &amp; Bar.suffix`.

**Comment by JakFrost** [comment]
Unsubscribe

**Comment by JakFrost** [comment]
unsubscribe

**Comment by the-real-tokai** [comment]
Just for completeness an example for the "&amp;" issue: it would happen with episode 13 of season 26 of http://epguides.com/Simpsons/, the file name becomes like `The Simpsons S26E14 Walking Big &amp; Tall.mp4`.

**Comment by fwenzel** [comment]
Another example of junk: http://epguides.com/Archer/

**Comment by fwenzel** [comment]
I broke out htm encoding because it's a different bug.
