### ISSUE TITLE
Decode HTML encoding in names

### ISSUE THREAD

**Issue by fwenzel** [meermanr/TVSeriesRenamer#22]
From #21:

> Another problem that I sometimes notice is that &amp; ends up as part of the episode title in the filenames rather than just &, e.g. `Series S00E00 Foo &amp; Bar.suffix`.
> Just for completeness an example for the `&amp;` issue: it would happen with episode 13 of season 26 of http://epguides.com/Simpsons/, the file name becomes like `The Simpsons S26E14 Walking Big &amp; Tall.mp4`.

**Comment by awmt102** [comment]
The &amp; specific issue can be fixed by adding the following after line 1409:

`s/&amp\;/&/;`

If i get a change I will submit a fixed file.

**Comment by fwenzel** [comment]
This works, though there might be other HTML entities also. What about `&ndash;` etc.

**Comment by awmt102** [comment]
Good point... new solution: 

add `use HTML::Entities;` at the top of the file (e.g. line 75) and add `$after = decode_entities($after);` immediately after `$after = $_;`
