### ISSUE TITLE
EpGuides.com format has changed.

### ISSUE THREAD

**Issue by alpha-ghosh** [meermanr/TVSeriesRenamer#25]
TV Series Renamer v2.56
Released 24 April 2012
Detected series name 'Homeland' (Season 7)
Reading input in AutoFetch mode from EpGuides.com
Input is URL: http://epguides.com/Homeland/
Will not look for cache file
Fetching document http://epguides.com/Homeland/... [Done]
No useable results. Trying: TV.com
Search URL: http://www.tv.com/index.php?type=Search&stype=ajax_search&qs=Homelan
d&search_type=program&pg_results=0&sort=
Performing search...
Problem with server (received 0 bytes)...
Performing search...
Problem with server (received 0 bytes)...
Performing search...
Problem with server (received 0 bytes)...
Unable to perform search on TV.com! (Fetched  bytes of data) Please try the foll
owing in a browser:
  http://www.tv.com/index.php?type=Search&stype=ajax_search&qs=Homeland&search_t
ype=program&pg_results=0&sort=
at /cygdrive/c/bin/tvrenamer.pl line 693.

**Comment by meermanr** [comment]
I think this is fixed in v2.57 (just pushed) - please let me know if the new `tvrenamer.exe` works for you, I'm using a new method to produce it using [Strawberry Perl](http://strawberryperl.com/) + [PAR Packager](https://metacpan.org/pod/pp)

**Comment by alpha-ghosh** [comment]
Fixed!  Thanks Robert.
